language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
install:
  - sudo apt-get install build-essential gfortran python-dev python-numpy python-setuptools python-scipy libatlas-dev libatlas-base-dev
  - pip install -q -r requirements.txt
  - pip install -q coveralls
script:
  - python setup.py test 
after_success:
  - coveralls

