language: python
virtualenv:
  system_site_packages: true
env:
  matrix:
    - DISTRIB="ubuntu" PYTHON_VERSION="2.7" COVERAGE="true"
    - DISTRIB="conda" PYTHON_VERSION="3.4"
      NUMPY_VERSION="1.9.1" SCIPY_VERSION="0.14.0"
install:
  - source tests/install.sh
  - pip install -vq -r requirements.txt
script:
  - python setup.py test 
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
cache:
  - apt
